export const CONFIG = {
  GRID_SIZE: 7,
  MAX_FLOORS: 5,
  PLAYER_MAX_HP: 20,
  MAX_ORBS: 5,

  // Damage
  SINGLE_ORB_DAMAGE: 3,
  MIXED_DAMAGE: 5,
  WEAKNESS_MULTIPLIER: 2,
  RESISTANCE_MULTIPLIER: 0.5,
  POISON_DAMAGE_PER_TURN: 2,
  POISON_TURNS: 3,
  AOE_DAMAGE: 3,
  HEAL_AMOUNT: 6,

  // Enemy base stats per floor
  ENEMY_BASE_HP: 6,
  ENEMY_HP_PER_FLOOR: 3,
  ENEMY_BASE_DAMAGE: 2,
  ENEMY_DAMAGE_PER_FLOOR: 1,
  ENEMIES_PER_FLOOR: 3,
  ENEMIES_EXTRA_PER_FLOOR: 1,

  // Boss
  BOSS_HP_MULTIPLIER: 3,
  BOSS_DAMAGE_MULTIPLIER: 2,

  // Pickups
  ORBS_PER_FLOOR: 3,
  ORBS_EXTRA_PER_FLOOR: 1,

  // Score
  SCORE_PER_ENEMY: 10,
  SCORE_PER_FLOOR: 50,
  SCORE_EFFICIENCY_BONUS: 5,

  // Walls
  WALL_COUNT_BASE: 5,
  WALL_COUNT_PER_FLOOR: 2,
} as const;
